export const initialStudentCourses = [
  {
    id: 'sc-cs401',
    code: 'CS-401',
    title: 'Advanced Neural Architectures & Systems',
    department: 'Computer Science & Cybernetics',
    section: 'Sec. 01',
    credits: 4,
    instructorName: 'Prof. Eleanor Vance, Ph.D.',
    instructorTitle: 'Chair of Cybernetic Engineering',
    instructorAvatar:
      'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=256',
    instructorOffice: 'Alan Turing Engineering Complex #412',
    schedule: 'Mon & Wed \u2022 10:00 AM \u2013 11:30 AM EST',
    room: 'Amphitheater L-102 \u2022 Lecture',
    attendanceRate: 98,
    presentSessions: 49,
    totalSessions: 50,
    standing: 'EXEMPLARY \u2022 HONORS',
    threshold: 85,
    isEnrolled: true,
    upcomingNotice: {
      time: 'HAPPENING TODAY \u2022 10:00 AM',
      title: 'Lecture 18: Attention Mechanisms & Sparsity',
      description: 'Assigned readings: Vaswani et al. \xA73.2',
    },
    syllabusWeeks: [
      {
        week: 'WEEK 06 (CURRENT)',
        title: 'Attention Sparsity & FlashAttention-2',
        isCurrent: true,
      },
      { week: 'WEEK 07', title: 'Transformer Scaling Laws' },
      { week: 'WEEK 08', title: 'Distributed Mixture of Experts' },
    ],
    repos: [
      {
        type: 'slides',
        label: 'Lecture Slides',
        sub: 'Week 6 Sparsity.pdf...',
      },
      {
        type: 'repo',
        label: 'GitHub Lab Repo',
        sub: 'github.com/othello-inst/cs401-transformers',
      },
      { type: 'forum', label: 'Forum #neural-nlp', sub: '14 Unread Posts' },
    ],
  },
  {
    id: 'sc-swe210',
    code: 'SWE-210',
    title: 'Full-Stack Enterprise Engineering',
    department: 'Software Systems',
    section: 'Sec. 03',
    credits: 3.5,
    instructorName: 'Dr. Maya Lin',
    instructorTitle: 'Distinguished Research Fellow',
    instructorAvatar:
      'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=256',
    instructorOffice: 'Tech Hall B-210',
    schedule: 'Tue & Thu \u2022 09:00 AM \u2013 10:30 AM EST',
    room: 'Tech Hall B-12 \u2022 Studio Lab',
    attendanceRate: 95,
    presentSessions: 38,
    totalSessions: 40,
    standing: 'GOOD STANDING',
    threshold: 85,
    isEnrolled: true,
    upcomingNotice: {
      time: 'TOMORROW \u2022 09:00 AM',
      title: 'Sprint 4 Code Review & CI/CD Pipeline',
      description: 'Bring Docker artifacts for cluster deploy',
    },
    syllabusWeeks: [
      {
        week: 'WEEK 06 (CURRENT)',
        title: 'Distributed Tracing with OpenTelemetry',
        isCurrent: true,
      },
      { week: 'WEEK 07', title: 'Zero-Downtime Blue/Green Deployments' },
      { week: 'WEEK 08', title: 'Event-Driven Microservice Choreography' },
    ],
    repos: [
      { type: 'slides', label: 'Lab Guidelines', sub: 'Sprint4_CI_CD.pdf' },
      {
        type: 'repo',
        label: 'GitHub Monorepo',
        sub: 'github.com/othello-inst/swe210-enterprise',
      },
      { type: 'forum', label: 'DevOps Slack', sub: 'Channel #sprint-help' },
    ],
  },
  {
    id: 'sc-ai490',
    code: 'AI-490',
    title: 'Deep Reinforcement Learning Seminar',
    department: 'Artificial Intelligence',
    section: 'Honors Colloquium',
    credits: 4,
    instructorName: 'Dr. Aris Thorne',
    instructorTitle: 'Principal Scientist, AI Lab',
    instructorAvatar:
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
    instructorOffice: 'Cybernetics Wing C-302',
    schedule: 'Mon & Fri \u2022 14:00 PM \u2013 15:30 PM EST',
    room: 'Cybernetics Suite A-204',
    attendanceRate: 96,
    presentSessions: 24,
    totalSessions: 25,
    standing: 'GOOD STANDING',
    threshold: 85,
    isEnrolled: true,
    upcomingNotice: {
      time: 'MONDAY \u2022 14:00 PM',
      title: 'Policy Gradient Bounds Seminar',
      description: 'Student paper defense: PPO vs TRPO',
    },
    syllabusWeeks: [
      {
        week: 'WEEK 06 (CURRENT)',
        title: 'Proximal Policy Optimization & Generalized Advantage',
        isCurrent: true,
      },
      { week: 'WEEK 07', title: 'Model-Based Planning (MuZero)' },
      { week: 'WEEK 08', title: 'Multi-Agent RL & Stochastic Games' },
    ],
    repos: [
      {
        type: 'slides',
        label: 'Seminar Papers',
        sub: 'PPO_TRPO_Derivations.pdf',
      },
      {
        type: 'repo',
        label: 'Gymnasium Simulation',
        sub: 'github.com/othello-inst/ai490-rl',
      },
      { type: 'forum', label: 'Lab ArXiv Club', sub: '8 Comments' },
    ],
  },
  {
    id: 'sc-math240',
    code: 'MATH-240',
    title: 'Discrete Mathematics & Cryptography',
    department: 'Applied Mathematics',
    section: 'Sec. 02',
    credits: 3.5,
    instructorName: 'Dr. Elena Rostova',
    instructorTitle: 'Associate Dean of Cryptographic Studies',
    instructorAvatar:
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=256',
    instructorOffice: 'Cantor Hall #104',
    schedule: 'Tue & Thu \u2022 13:00 PM \u2013 14:30 PM EST',
    room: 'Cantor Hall 3 \u2022 Lecture & Boardwork',
    attendanceRate: 91.7,
    presentSessions: 33,
    totalSessions: 36,
    standing: 'IN COMPLIANCE',
    threshold: 85,
    isEnrolled: true,
    upcomingNotice: {
      time: 'THURSDAY \u2022 13:00 PM',
      title: 'Elliptic Curves & Zero-Knowledge Proofs',
      description: 'Homework 5 due before class commencement',
    },
    syllabusWeeks: [
      {
        week: 'WEEK 06 (CURRENT)',
        title: 'Elliptic Curve Point Arithmetic & Weil Pairing',
        isCurrent: true,
      },
      { week: 'WEEK 07', title: 'zk-SNARKs & Groth16 Proof Verification' },
      { week: 'WEEK 08', title: 'Lattice-Based Post-Quantum Cryptography' },
    ],
    repos: [
      {
        type: 'slides',
        label: 'Boardwork Proofs',
        sub: 'EllipticCurves_Notes.pdf',
      },
      {
        type: 'repo',
        label: 'SageMath Notebooks',
        sub: 'github.com/othello-inst/math240-crypto',
      },
      { type: 'forum', label: 'Proof Office Hours', sub: 'Wed 16:00 Cantor' },
    ],
  },
  {
    id: 'sc-eth310',
    code: 'ETH-310',
    title: 'Cognitive Ethics & AI Governance',
    department: 'Capstone Foundation',
    section: 'Sec. 01',
    credits: 3,
    instructorName: 'Dean Marcus Aurel',
    instructorTitle: 'Dean of Applied Philosophy',
    instructorAvatar:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256',
    instructorOffice: 'Ethics Forum Hall 1',
    schedule: 'Wednesdays \u2022 15:30 PM \u2013 17:00 PM EST',
    room: 'Ethics Forum 1 \u2022 Socratic Seminar',
    attendanceRate: 100,
    presentSessions: 14,
    totalSessions: 14,
    standing: 'PERFECT',
    threshold: 85,
    isEnrolled: true,
    upcomingNotice: {
      time: 'WEDNESDAY \u2022 15:30 PM',
      title: 'Algorithmic Accountability & EU AI Act',
      description: 'Pre-read EU AI Act Annex III',
    },
    syllabusWeeks: [
      {
        week: 'WEEK 06 (CURRENT)',
        title: 'EU AI Act Annex III Compliance Auditing',
        isCurrent: true,
      },
      {
        week: 'WEEK 07',
        title: 'Dual-Use AI Safety & Model Alignment Governance',
      },
      { week: 'WEEK 08', title: 'Autonomous Systems & Liability Frameworks' },
    ],
    repos: [
      {
        type: 'slides',
        label: 'Policy Whitepaper',
        sub: 'EU_AI_Act_Annotated.pdf',
      },
      {
        type: 'repo',
        label: 'Case Studies Archive',
        sub: 'github.com/othello-inst/eth310-cases',
      },
      {
        type: 'forum',
        label: 'Socratic Discourse',
        sub: 'Topic: Algorithmic Biases',
      },
    ],
  },
];
export const initialStudentElectives = [
  {
    id: 'elec-cs520',
    code: 'CS-520',
    title: 'Distributed Systems & Consensus Protocols',
    department: 'Department of Computer Science',
    tag: 'Elective Track',
    credits: 4,
    seatsOpen: 28,
    totalSeats: 35,
    instructorName: 'Prof. Eleanor Vance, Ph.D.',
    instructorTitle: 'Chair of Cybernetic Engineering',
    instructorAvatar:
      'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=256',
    instructorOfficeHours: 'OH: Wed 15:00 \u2022 Hall D-112',
    schedule: 'Tuesdays & Thursdays \u2022 16:00 PM \u2013 17:30 PM EST',
    room: 'Lab Hall D-1 \u2022 Studio Cluster 4 \u2022 Alan Turing Complex',
    description:
      'In-depth investigation of peer-to-peer topologies, Paxos/Raft quorum consensus algorithms, Byzantine fault tolerance, and high-throughput transactional replication.',
    qualifiesRequirement: 'Satisfies Senior Systems Elective Core',
    conflictCheck:
      'No Timetable Conflicts with Enrolled Courses (CS-401, SWE-210, AI-490, MATH-240, ETH-310)',
    term: 'Term 2025-A: Jan 13 \u2013 May 18, 2025',
    isEnrolled: false,
    milestones: [
      {
        weeks: 'Weeks 1-4: Foundations',
        title: 'Foundations',
        description: 'Fault tolerance models, Paxos & Raft consensus quorum.',
      },
      {
        weeks: 'Weeks 5-8: Byzantine Faults',
        title: 'Byzantine Faults',
        description: 'Byzantine agreement, state machine replication logs.',
      },
      {
        weeks: 'Weeks 9-12: Network Gossip',
        title: 'Network Gossip',
        description: 'Peer-to-peer topologies, epidemic dissemination.',
      },
      {
        weeks: 'Weeks 13-16: Capstone Engine',
        title: 'Capstone Engine',
        description: 'Distributed key-value store final defense.',
      },
    ],
  },
  {
    id: 'elec-cyber350',
    code: 'CYBER-350',
    title: 'Network Defense & Threat Modelling',
    department: 'Center for Security Research',
    tag: 'Security Core',
    credits: 3.5,
    seatsOpen: 14,
    totalSeats: 30,
    instructorName: 'Dr. Marcus Aurel',
    instructorTitle: 'Director of Applied Defensive Security',
    instructorAvatar:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256',
    instructorOfficeHours: 'OH: Mon 16:30 \u2022 Cyber Lab 3',
    schedule: 'Mondays & Wednesdays \u2022 15:00 PM \u2013 16:30 PM EST',
    room: 'Cyber Lab 3 \u2022 Red Team Range',
    description:
      'Hands-on offensive and defensive cybersecurity architectures, zero-trust network packet inspection, cryptographic attestation, and live enterprise red team sandboxes.',
    qualifiesRequirement: 'Fulfills Advanced Cybersecurity Elective',
    conflictCheck: 'No Schedule Overlap with CS-401 or SWE-210',
    term: 'Term 2025-A: Jan 13 \u2013 May 18, 2025',
    isEnrolled: false,
    milestones: [
      {
        weeks: 'Weeks 1-4: Perimeter Defense',
        title: 'Perimeter Defense',
        description:
          'EBPF network firewalls, zero-trust boundary segmentation.',
      },
      {
        weeks: 'Weeks 5-8: Cryptographic Attestation',
        title: 'Cryptographic Attestation',
        description: 'Hardware security modules, TPM 2.0 enclave verification.',
      },
      {
        weeks: 'Weeks 9-12: Attack Graph Modelling',
        title: 'Attack Graph Modelling',
        description: 'STRIDE taxonomy, MITRE ATT&CK kill-chain mapping.',
      },
      {
        weeks: 'Weeks 13-16: Live Red/Blue Sandbox',
        title: 'Live Red/Blue Sandbox',
        description: 'Active enterprise intrusion simulation & forensic audit.',
      },
    ],
  },
  {
    id: 'elec-ui310',
    code: 'UI-310',
    title: 'Advanced Human-Computer Interaction & Systems Design',
    department: 'Department of Interactive Systems',
    tag: 'HCI Elective',
    credits: 3,
    seatsOpen: 8,
    totalSeats: 30,
    instructorName: 'Dr. Priya Sharma, M.Des.',
    instructorTitle: 'Director of Interaction Lab',
    instructorAvatar:
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
    instructorOfficeHours: 'OH: Thu 11:00 \u2022 Design Studio 2',
    schedule: 'Wednesdays \u2022 14:00 PM \u2013 17:00 PM EST',
    room: 'Design Studio 2 \u2022 Prototyping Bay',
    description:
      'Cognitive ergonomics, rapid micro-interaction prototyping, accessible universal design systems, neuro-adaptive interfaces, and qualitative user behavioral telemetry.',
    qualifiesRequirement: 'Qualifies for CS Human-Centered Track Focus',
    conflictCheck:
      'Partial overlap on Wednesday afternoon; lab sessions asynchronously scheduled',
    term: 'Term 2025-A: Jan 13 \u2013 May 18, 2025',
    isEnrolled: false,
    milestones: [
      {
        weeks: 'Weeks 1-4: Cognitive Models',
        title: 'Cognitive Models',
        description:
          'Fitts Law, Hick-Hyman decision latency, visual hierarchy.',
      },
      {
        weeks: 'Weeks 5-8: Spatial Computing & Ergonomics',
        title: 'Spatial Ergonomics',
        description:
          'Gesture affordances, dynamic haptics, multi-modal feedback.',
      },
      {
        weeks: 'Weeks 9-12: Accessible Systems',
        title: 'Accessible Systems',
        description:
          'WCAG AAA design engineering, screen-reader kinetic navigation.',
      },
      {
        weeks: 'Weeks 13-16: Prototype Showcase',
        title: 'Prototype Showcase',
        description: 'Full interactive human-centered software critique.',
      },
    ],
  },
  {
    id: 'elec-ds302',
    code: 'DS-302',
    title: 'Applied Data Infrastructure & Streaming Pipelines',
    department: 'Data Architecture Group',
    tag: 'Systems Elective',
    credits: 4,
    seatsOpen: 19,
    totalSeats: 40,
    instructorName: 'Dr. Maya Lin',
    instructorTitle: 'Distinguished Research Fellow',
    instructorAvatar:
      'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=256',
    instructorOfficeHours: 'OH: Mon 10:00 \u2022 Data Wing B-04',
    schedule: 'Fridays \u2022 10:00 AM \u2013 13:00 PM EST',
    room: 'Data Wing B-04 \u2022 Streaming Cluster',
    description:
      'Distributed streaming architectures utilizing Apache Kafka, real-time feature stores, columnar OLAP engines, and continuous data audit pipelines.',
    qualifiesRequirement: 'Fulfills Advanced Data Infrastructure Requirement',
    conflictCheck: 'No Timetable Conflicts with Enrolled Courses',
    term: 'Term 2025-A: Jan 13 \u2013 May 18, 2025',
    isEnrolled: false,
    milestones: [
      {
        weeks: 'Weeks 1-4: Event Streaming',
        title: 'Event Streaming',
        description:
          'Kafka partition topologies, exactly-once delivery semantics.',
      },
      {
        weeks: 'Weeks 5-8: State Stores & RocksDB',
        title: 'State Stores & RocksDB',
        description: 'Stream joins, sliding tumbling window aggregations.',
      },
      {
        weeks: 'Weeks 9-12: Columnar Engines',
        title: 'Columnar Engines',
        description: 'ClickHouse, Apache Arrow, vectorized query execution.',
      },
      {
        weeks: 'Weeks 13-16: Real-time ML Pipeline',
        title: 'Real-time ML Pipeline',
        description: 'Sub-millisecond inference telemetry pipeline defense.',
      },
    ],
  },
];
export const initialStudentAuditRecords = [
  {
    id: 'audit-50',
    sessionNumber: 50,
    courseCode: 'CS-401',
    courseTitle: 'Advanced Neural Architectures',
    instructor: 'Prof. Eleanor Vance, Ph.D.',
    date: 'Today, Nov 12',
    timestamp: '10:02 AM',
    scheduleTime: '10:00 AM \u2013 11:30 AM',
    telemetryCheckIn: '09:58:14 AM (Gate L-102)',
    ingressDevice: 'Turnstile Gate #4',
    room: 'Amphitheater L-102',
    status: 'PRESENT',
    notes: 'Lecture 18: Attention Mechanisms \u2022 Verified by Prof. Vance',
  },
  {
    id: 'audit-39',
    sessionNumber: 39,
    courseCode: 'SWE-210',
    courseTitle: 'Full-Stack Enterprise Eng',
    instructor: 'Dr. Maya Lin',
    date: 'Yesterday, Nov 11',
    timestamp: '09:04 AM',
    scheduleTime: '09:00 AM \u2013 10:30 AM',
    telemetryCheckIn: '08:55:02 AM (RFID Tech B-12)',
    ingressDevice: 'Turnstile Tech-12',
    room: 'Tech Hall B-12',
    status: 'PRESENT',
    notes: 'Sprint 4 Architecture Walkthrough \u2022 Lab submission recorded',
  },
  {
    id: 'audit-24',
    sessionNumber: 24,
    courseCode: 'AI-490',
    courseTitle: 'Reinforcement Learning',
    instructor: 'Dr. Aris Thorne',
    date: 'Mon, Nov 10',
    timestamp: '14:07 AM',
    scheduleTime: '14:00 PM \u2013 15:30 PM',
    telemetryCheckIn: '14:02:11 PM (Geofence A-204)',
    ingressDevice: 'Turnstile Suite A',
    room: 'Suite A-204 Research',
    status: 'LATE',
    notes: 'Student Defense: PPO vs TRPO algorithms \u2022 +7m grace',
  },
  {
    id: 'audit-35',
    sessionNumber: 35,
    courseCode: 'MATH-240',
    courseTitle: 'Discrete Math & Cryptography',
    instructor: 'Dr. Elena Rostova',
    date: 'Thu, Nov 6',
    timestamp: '13:00 PM',
    scheduleTime: '13:00 PM \u2013 14:30 PM',
    telemetryCheckIn: '\u2014 (No Gate Badge)',
    ingressDevice: 'Cantor Hall Node',
    room: 'Cantor Hall 3',
    status: 'UNEXCUSED',
    notes: 'Zero-Knowledge Proofs Intro \u2022 Unexcused, 2 absences remaining',
  },
  {
    id: 'audit-14',
    sessionNumber: 14,
    courseCode: 'ETH-310',
    courseTitle: 'Cognitive Ethics & AI',
    instructor: 'Dean Marcus Aurel',
    date: 'Wed, Nov 5',
    timestamp: '15:28 PM',
    scheduleTime: '15:30 PM \u2013 17:00 PM',
    telemetryCheckIn: '15:26:40 PM (Gate Ethics-1)',
    ingressDevice: 'Turnstile Eth-01',
    room: 'Ethics Forum 1',
    status: 'PRESENT',
    notes: 'Algorithmic Accountability & EU AI Act discussion',
  },
  {
    id: 'audit-48',
    sessionNumber: 48,
    courseCode: 'CS-401',
    courseTitle: 'Advanced Neural Architectures',
    instructor: 'Prof. Eleanor Vance, Ph.D.',
    date: 'Mon, Nov 3',
    timestamp: '10:00 AM',
    scheduleTime: '10:00 AM \u2013 11:30 AM',
    telemetryCheckIn: 'MED-9921',
    ingressDevice: 'Campus Health Portal',
    room: 'Amphitheater L-102',
    status: 'EXCUSED',
    notes: 'Approved by Academic Advising \u2022 Health Center clearance',
  },
  {
    id: 'audit-37',
    sessionNumber: 37,
    courseCode: 'SWE-210',
    courseTitle: 'Full-Stack Enterprise Eng',
    instructor: 'Dr. Maya Lin',
    date: 'Thu, Oct 30',
    timestamp: '08:59 AM',
    scheduleTime: '09:00 AM \u2013 10:30 AM',
    telemetryCheckIn: '08:59:12 AM (RFID Tech B-12)',
    ingressDevice: 'Turnstile Tech-12',
    room: 'Tech Hall B-12',
    status: 'PRESENT',
    notes: 'Microservices CI/CD Pipeline Lab Session',
  },
];
export {
  initialStudentCourses as studentCoursesInitial,
  initialStudentElectives as studentElectivesInitial,
  initialStudentAuditRecords as studentAuditRecordsInitial,
};
export const upcomingStudentSessions = [
  {
    id: 'up-1',
    courseCode: 'CS-401',
    title: 'Lecture 18 \u2014 Attention Mechanisms & Sparsity',
    instructor: 'Prof. Vance',
    room: 'Amphitheater L-102',
    dateBadge: 'TODAY \u2022 10:00 - 11:30 AM',
    statusBadge: 'Starts in 40m',
    isPrimary: true,
    actionType: 'checkin',
  },
  {
    id: 'up-2',
    courseCode: 'AI-490',
    title: 'Policy Gradient Bounds Laboratory',
    instructor: 'Dr. Thorne',
    room: 'Cybernetics Suite A-204',
    dateBadge: 'TODAY \u2022 14:00 - 15:30 PM',
    statusBadge: 'Lab Practicum',
    actionType: 'virtual_node',
  },
  {
    id: 'up-3',
    courseCode: 'SWE-210',
    title: 'Sprint 4 Review & Architecture Walkthrough',
    instructor: 'Dr. Maya Lin',
    room: 'Tech Hall B-12',
    dateBadge: 'TOMORROW \u2022 09:00 - 10:30 AM',
    statusBadge: 'Review Session',
  },
  {
    id: 'up-4',
    courseCode: 'MATH-240',
    title: 'Elliptic Curves & Zero-Knowledge Proofs',
    instructor: 'Dr. Elena Rostova',
    room: 'Cantor Hall 3',
    dateBadge: 'THURSDAY \u2022 13:00 - 14:30 PM',
    statusBadge: 'Problem Set Due',
  },
];
export const studentBulletins = [
  {
    id: 'bul-1',
    author: 'Prof. Eleanor Vance',
    avatar:
      'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=256',
    time: '12m ago',
    title: 'Uploaded updated slide deck for Lecture 18 with corrected...',
    attachment: 'Lec18_Attention.pdf',
  },
  {
    id: 'bul-2',
    author: 'Dr. Maya Lin',
    avatar:
      'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=256',
    time: '3h ago',
    title: 'Sprint 4 architecture guidelines published. Review your...',
    tag: 'Due Nov 14, 23:59',
  },
  {
    id: 'bul-3',
    author: 'Office of the Registrar',
    avatar:
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=256',
    time: 'Yesterday',
    title: 'Spring 2025 registration portal opens on November 20. Confirm...',
    sub: 'Degree Audit Cleared',
  },
];
